service: secure-notes
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  environment:
    NOTES_TABLE: notes
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: !GetAtt NotesTable.Arn

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  create:
    handler: bin/create
    events:
      - http:
          path: notes
          method: post
  get:
    handler: bin/get
    events:
      - http:
          path: notes/{id}
          method: get

resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes
        AttributeDefinitions:
          -
            AttributeName: pk
            AttributeType: S
        KeySchema:
          -
            AttributeName: pk
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
